# name = input("Enter your full name: ")
phone_number = input("Enter your phone number: ")

# result = len(name)
# result = name.find("o")
# result = name.rfind("q")
# result = name.capitalize()
# result = name.upper()
# result = name.lower()
# result = name.isdigit()
# result = name.isalpha()
# result = phone_number.count("-")
# phone_number = phone_number.replace("-", "")